### ISSUE TITLE
Create navbar

### ISSUE THREAD

**Issue by FemboyDeveloper** [FemboyDeveloper/AW-Competitive#1]
Create a navigation bar component for the website.

You see how here we have a regular navigation bar (on the top) and a user specific navigation bar? we need both. Take AWBW navbar as inspiration, not as a carbon copy of what you must do. For example, we need at the top a Home, Games, FAQ, our Github and discord if we make one and a login/register section.

For the user page, mostly a profile page and my games (games you are part of)
![Image](https://user-images.githubusercontent.com/96269542/215839384-93568da5-8bd0-44e1-98a8-a91c9e06f1af.png)

**Comment by JaviTrek** [comment]
We need to wait for the code to be committed in a branch and then we can close these issues.
